#!/bin/bash

export PATH="$PATH:$HOME/bin"
pulseaudio --start
xsetroot -cursor_name left_ptr
setxkbmap -option caps:escape

[[ "$(which xscreensaver)" == "/usr/bin/xscreensaver" ]] && /usr/bin/xscreensaver -no-splash &
[[ "$(which nm-applet)" == "/usr/bin/nm-applet" ]] && /usr/bin/nm-applet &
[[ -f ~/.screenlayout/main.sh ]] && ~/.screenlayout/main.sh

#which compton && compton -b

urxvtd -q -o -f &
